<a href="https://colab.research.google.com/github/gupteshmahale04-arch/Pandas/blob/main/pandas_class6_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pandas Class 6 Assignment

## Level: Basic to Intermediate

### Instructions
- Solve all questions using Pandas.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display Unique Values

## Problem Statement
Create a DataFrame with a City column and display all unique cities.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
['Bhopal' 'Indore' 'Delhi']
```

In [4]:
# Write your code here
import pandas as pd
d=pd.DataFrame({"City": ["Bhopal", "Indore", "Bhopal", "Delhi"]})
d["City"].unique()

array(['Bhopal', 'Indore', 'Delhi'], dtype=object)


# Q2. Count Unique Values

## Problem Statement
Find the number of unique cities in a DataFrame.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
3
```

In [ ]:
# Write your code here
d["City"].nunique()


# Q3. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
Bhopal    2
Indore    1
Delhi     1
```

In [5]:
# Write your code here
d["City"].value_counts()

City
Bhopal    2
Indore    1
Delhi     1
Name: count, dtype: int64


# Q4. Group By City

## Problem Statement
Find average marks city-wise using groupby().

## Sample Input
```python
City   Marks
Bhopal 80
Bhopal 90
Delhi  70
```

## Sample Output
```python
Bhopal 85
Delhi  70
```

In [6]:
# Write your code here
d=pd.DataFrame({"City": ["Bhopal", "Indore", "Bhopal", "Delhi"],"Marks":[80,90,70,70]})
d.groupby("City").mean()

        Marks
City
Bhopal   75.0
Delhi    70.0
Indore   90.0


# Q5. Sort Values

## Problem Statement
Sort students by Marks in ascending order.

## Sample Output
```python
Sorted DataFrame
```

In [8]:
# Write your code here
d.sort_values("Marks")

     City  Marks
3   Delhi     70
2  Bhopal     70
0  Bhopal     80
1  Indore     90


# Q6. Sort Values Descending

## Problem Statement
Sort students by Marks in descending order.

## Sample Output
```python
Sorted DataFrame
```

In [ ]:
# Write your code here
d.sort_values("Marks",ascending=False)


# Q7. Filter Records

## Problem Statement
Display students having marks greater than 75.

## Sample Output
```python
Filtered rows
```

In [9]:
# Write your code here
d[d["Marks"]>75]


# Q8. Multiple Conditions

## Problem Statement
Display students whose marks are greater than 70 and age is greater than 20.

## Sample Output
```python
Filtered rows
```

In [11]:
# Write your code hered
d[["City","Marks"]][(d["Marks"]>70) & (d["City"]=="Bhopal")]

     City  Marks
0  Bhopal     80


# Q9. Group By Department

## Problem Statement
Create Employee and Department data and find total salary department-wise.

## Sample Output
```python
HR       50000
IT      120000
```

In [13]:
# Write your code here
d=pd.DataFrame({
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]



})
d.groupby("Department").sum()["Salary"]

Department
Finance    183000
HR         102000
IT         217000
Name: Salary, dtype: int64


# Q10. Complete Practice Question

## Problem Statement
Create a DataFrame containing:
- Name
- Age
- City
- Marks

Perform:
1. Show unique cities
2. Count city frequency
3. Filter marks > 80
4. Sort by marks

## Sample Output
```python
Required Results
```

In [27]:
# Write your code here
import pandas as pd
d=pd.DataFrame({
    "Name ":["Rohan ","Raj","Roky","Rahul",],
    "Age":[12,25,21,25],
    "City":["Bhopal","Indore","Bhopal","Delhi"],
    "Marks":[80,90,70,70]
})
d.City.unique()
d.City.value_counts()
d[d['Marks']> 80]
d.sort_values("Marks")

    Name   Age    City  Marks
3   Rahul   25   Delhi     70
2    Roky   21  Bhopal     70
0  Rohan    12  Bhopal     80
1     Raj   25  Indore     90