<a href="https://colab.research.google.com/github/gupteshmahale04-arch/Pandas/blob/main/Pandas_Class5_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Class 5 Assignment

## Topics
- sort_values()
- mean()
- median()
- mode()
- value_counts()
- corr()
- cov()

Difficulty: Easy to Moderate

## Q1. Sort Age in Ascending Order

Input:
Age = [25, 18, 30, 22]

Output:
18
22
25
30

In [ ]:
# Write your code here
import pandas as pd
d=pd.DataFrame({"Age":[25, 18, 30, 22],

                })
d.sort_values(by="Age")

   Age
1   18
3   22
0   25
2   30

## Q2. Sort Marks in Descending Order

Input:
Marks = [70, 95, 80, 60]

Output:
95
80
70
60

In [ ]:
# Write your code hereimport pandas as pd
d=pd.DataFrame({
                 "Marks" : [70, 95, 80, 60]
                 })
print(d.sort_values(by="Marks",ascending=False))

   Marks
1     95
2     80
0     70
3     60

## Q3. Find Mean Age

Input:
Age = [20, 25, 30, 25]

Output:
25.0

In [ ]:
# Write your code hereimport pandas as pd
d=pd.DataFrame({"Age": [20, 25, 30, 25]})
print(d.mean())

Age    25.0
dtype: float64

## Q4. Find Median Marks

Input:
Marks = [50, 60, 70, 80, 90]

Output:
70

In [ ]:
# Write your code here
d=pd.DataFrame({"Age": [50, 60, 70, 80, 90]})
print(d.median)

<bound method DataFrame.median of    Age
0   50
1   60
2   70
3   80
4   90>

## Q5. Find Mode

Input:
Age = [20, 25, 25, 30, 25]

Output:
25

In [ ]:
# Write your code here
d=pd.DataFrame({" Age ": [20, 25, 25, 30, 25]})
print(d.mode())

   Age
0    25

## Q6. Find Maximum Score

Input:
Score = [78, 90, 67, 88]

Output:
90

In [ ]:
# Write your code here
d=pd.DataFrame({"Score":[78, 90, 67, 88]})
print(d.max())

Score    90
dtype: int64

## Q7. Find Minimum Score

Input:
Score = [78, 90, 67, 88]

Output:
67

In [ ]:
# Write your code here
d=pd.DataFrame({"Score":[78, 90, 67, 88]})
print(d.min())

Score    67
dtype: int64

## Q8. Count City Frequency

Input:
City = ['Bhopal','Indore','Bhopal','Jabalpur']

Output:
Bhopal      2
Indore      1
Jabalpur    1

In [ ]:
# Write your code here
d=pd.DataFrame({ "City" : ['Bhopal','Indore','Bhopal','Jabalpur']})
print(d.value_counts())

City
Bhopal      2
Indore      1
Jabalpur    1
Name: count, dtype: int64

## Q9. Find Percentage Frequency

Input:
City = ['A','A','B','C']

Output:
A = 50%
B = 25%
C = 25%

In [ ]:
# Write your code here
d=pd.DataFrame({ "City ": ['A','A','B','C']})
print(d.value_counts(normalize=True)*100)

City
A        50.0
B        25.0
C        25.0
Name: proportion, dtype: float64

## Q10. Sort DataFrame by Salary

Input:
Name   Salary
Aman   30000
Raj    50000
Riya   40000

Output:
Raj
Riya
Aman

In [ ]:
# Write your code here
import pandas as pd
d=pd.DataFrame({"Name":["Aman","Raj","Riya"],
                "Salary":[30000,50000,40000]

})
d.Name

0    Aman
1     Raj
2    Riya
Name: Name, dtype: object

## Q11. Find Correlation

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
1.0

In [ ]:
# Write your code here
import pandas as pd
d=pd.DataFrame({"Math":[10,20,30,40],
                "Science":[15,25,35,45]

})
d.corr()

         Math  Science
Math      1.0      1.0
Science   1.0      1.0

## Q12. Find Covariance

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
166.67 (approx)

In [ ]:
# Write your code here
import pandas as pd
d=pd.DataFrame({"Math":[10,20,30,40],
                "Science":[15,25,35,45]

})
d.cov()

               Math     Science
Math     166.666667  166.666667
Science  166.666667  166.666667

## Q13. Sort by Two Columns

Input:
Sort by City and then Age

Output:
Sorted DataFrame

In [ ]:
from numpy._core.fromnumeric import sort
# Write your code
d=pd.DataFrame({ "Name":["Aman","Raj","Riya"],
                "Age":[20,45,30],
                "City":["Bhopal","Indore","Bhopal"]
})
d.sort_values(by=["City","Age"])

   Name  Age    City
0  Aman   20  Bhopal
2  Riya   30  Bhopal
1   Raj   45  Indore

## Q14. Student Statistics

Input:
Marks = [60,70,80,90]

Output:
Mean = 75
Median = 75
Max = 90
Min = 60

In [ ]:
# Write your code here
d=pd.DataFrame({"Marks":[60,70,80,90]})
print(d.mean())
print(d.median())
print(d.max())
print(d.min())

Marks    75.0
dtype: float64
Marks    75.0
dtype: float64
Marks    90
dtype: int64
Marks    60
dtype: int64

## Q15. Mini Practice

Create a DataFrame with:
Name, Age, Score, Height

Tasks:
1. Sort by Score (Descending)
2. Find Mean Age
3. Find Median Height
4. Show Score Frequency

In [ ]:
# Write your code here
d=pd.DataFrame({ "Name":["Aman","Raj","Riya"],
                "Age":[20,45,30],
                "City":["Bhopal","Indore","Bhopal"],
                 "Score":[60,70,80],
                 "Height":[160,170,180]
})

d.sort_values(by="Score")
d.Age.mean()
d.Height.median()
d.Score.value_counts()

Score
60    1
70    1
80    1
Name: count, dtype: int64