<a href="https://colab.research.google.com/github/gupteshmahale04-arch/Pandas/blob/main/Pandas_Project_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy + Pandas Assignment
## Beginner to Intermediate (Project Based)

**Instructions:**
- Solve all questions.
- Use the same dataset for all Pandas questions.
- Write your solution in the code cell below each question.

## Dataset

| EmpID | Name | Department | Salary | Age |
|------:|------|------------|-------:|----:|
|101|Raj|IT|50000|24|
|102|Amit|HR|42000|28|
|103|Neha|IT|65000|26|
|104|Priya|Finance|58000|30|
|105|Rohan|HR|45000|25|

## Question 1

Create a NumPy array using the salary values:

Input:
```
[50000,42000,65000,58000,45000]
```

Output:
```
array([50000,42000,65000,58000,45000])
```

In [2]:
# Write your code here
import numpy as np
arr=np.array([50000,42000,65000,58000,45000])
print(arr)

[50000 42000 65000 58000 45000]

## Question 2

Using the NumPy array, find Total Salary, Average Salary and Maximum Salary.

Output:
```
Total Salary = 260000
Average Salary = 52000.0
Maximum Salary = 65000
```

In [3]:
# Write your code here
print("Total Salary =",arr.sum())
print("Average Salary =",arr.mean())
print("Maximum Salary =",arr.max())

Total Salary = 260000
Average Salary = 52000.0
Maximum Salary = 65000

## Question 3

Convert the NumPy array into a Pandas DataFrame.

Column Name: **Salary**

In [4]:
# Write your code here
import pandas as pd
df=pd.DataFrame({"Salary": arr})
print(df)

   Salary
0   50000
1   42000
2   65000
3   58000
4   45000

## Question 4

Create the Employee DataFrame using the given dataset.

Expected Output: Employee DataFrame

In [5]:
import pandas as pd
Employee=pd.DataFrame({
                        "Emp_ID":[101,102,103,104],
                        "Name":["Ram","Rina","Rohit","golu"],
                        "Department":["HR",'MR',"HOD",'PM'],
                        "Salary" :[1000,2000,3,4554],
                        "Age":[45,25,28,26],

                        })



print(Employee)

   Emp_ID   Name Department  Salary  Age
0     101    Ram         HR    1000   45
1     102   Rina         MR    2000   25
2     103  Rohit        HOD       3   28
3     104   golu         PM    4554   26

## Question 5

Display only the **Name** and **Salary** columns.

Expected Output:

| Name | Salary |
|------|-------:|
|Raj|50000|
|Amit|42000|
|Neha|65000|
|Priya|58000|
|Rohan|45000|

In [6]:
# Write your code here
(Employee[["Name","Salary"]])

    Name  Salary
0    Ram    1000
1   Rina    2000
2  Rohit       3
3   golu    4554

## Question 6

Using **iloc**, display the complete details of the **third employee**.

Expected Output:
```
EmpID 103
Name Neha
Department IT
Salary 65000
Age 26
```

In [7]:
# Write your code here
Employee.iloc [1]

Emp_ID         102
Name          Rina
Department      MR
Salary        2000
Age             25
Name: 1, dtype: object

## Question 7

Using **loc**, display only **Raj's Salary**.

Output:
```
50000
```

In [8]:
# Write your code here
Employee.loc [1,"Salary"]

np.int64(2000)

## Question 8

Display all employees whose Salary is greater than **50000**.

Expected Output:

| Name | Salary |
|------|-------:|
|Neha|65000|
|Priya|58000|

In [9]:
# Write your code here
Employee[Employee["Salary"]>1000]

   Emp_ID  Name Department  Salary  Age
1     102  Rina         MR    2000   25
3     104  golu         PM    4554   26

## Question 9

Create a new column named **Bonus**.

Formula:
```
Bonus = Salary * 0.10
```

Expected Output:

| Name | Salary | Bonus |
|------|-------:|------:|
|Raj|50000|5000|
|Amit|42000|4200|
|Neha|65000|6500|
|Priya|58000|5800|
|Rohan|45000|4500|

In [10]:
# Write your code here
Employee["Bonus"]=Employee["Salary"]*0.10
print(Employee)

   Emp_ID   Name Department  Salary  Age  Bonus
0     101    Ram         HR    1000   45  100.0
1     102   Rina         MR    2000   25  200.0
2     103  Rohit        HOD       3   28    0.3
3     104   golu         PM    4554   26  455.4

## Question 10

Update Amit's Salary from **42000** to **48000**.

Expected Output:
Amit -> 48000

In [11]:
# Write your code here
Employee[(Employee["Salary"]>=1000)&(Employee["Salary"]<=2000)]

   Emp_ID  Name Department  Salary  Age  Bonus
0     101   Ram         HR    1000   45  100.0
1     102  Rina         MR    2000   25  200.0

## Question 11

Replace **HR** with **Human Resource** in the Department column.

Expected Output:
Amit -> Human Resource
Rohan -> Human Resource

In [12]:
Employee['Department'] = Employee['Department'].replace('HR', 'Human Resource')
print(Employee)

   Emp_ID   Name      Department  Salary  Age  Bonus
0     101    Ram  Human Resource    1000   45  100.0
1     102   Rina              MR    2000   25  200.0
2     103  Rohit             HOD       3   28    0.3
3     104   golu              PM    4554   26  455.4

## Question 12

Sort the DataFrame according to Salary in **Descending Order**.

Expected Order:
Neha
Priya
Raj
Rohan
Amit

In [13]:
Employee_sorted = Employee.sort_values(by='Salary', ascending=False)
print(Employee_sorted)

   Emp_ID   Name      Department  Salary  Age  Bonus
3     104   golu              PM    4554   26  455.4
1     102   Rina              MR    2000   25  200.0
0     101    Ram  Human Resource    1000   45  100.0
2     103  Rohit             HOD       3   28    0.3

## Question 13

Find the **Average Salary** of each Department using **groupby()**.

Expected Output:
Finance -> 58000
HR -> 43500
IT -> 57500

In [14]:
# Write your code here
Employee.groupby('Department')['Salary'].mean()

Department
HOD                  3.0
Human Resource    1000.0
MR                2000.0
PM                4554.0
Name: Salary, dtype: float64

## Question 14

Set **EmpID** as the index of the DataFrame and display the updated DataFrame.

In [15]:
indexed_employee_df = Employee.set_index('Emp_ID')
print(indexed_employee_df)

         Name      Department  Salary  Age  Bonus
Emp_ID
101       Ram  Human Resource    1000   45  100.0
102      Rina              MR    2000   25  200.0
103     Rohit             HOD       3   28    0.3
104      golu              PM    4554   26  455.4

## Question 15

Create another DataFrame containing **EmpID** and **Experience** and merge it with the Employee DataFrame.

Second DataFrame:

| EmpID | Experience |
|------:|-----------:|
|101|2|
|102|5|
|103|3|
|104|6|
|105|4|

Expected Output: Final merged DataFrame with Experience column.

In [23]:
Experience = pd.DataFrame({
    'EmpID': [101, 102, 103, 104, 105],
    'Experience': [2, 5, 3, 6, 4]
})

merged_employee_df = pd.merge(Employee, Experience, on='EmpID', how='right')
print(merged_employee_df)

   EmpID  Experience_x  Experience_y
0    101             2             2
1    102             5             5
2    103             3             3
3    104             6             6
4    105             4             4